### PR TITLE
Coding standards

### PR DESCRIPTION
**Pull request by benoitchantre**
Apply WordPress Coding Standards.

### CODE REVIEW

**Comment by benoitchantre** [comment]
I was asking myself why there was no recurring options displayed.
After applying the coding standards, recurring options are displayed.

**Comment by billerickson** [comment]
Recent changes have caused conflicts.

**Comment by benoitchantre** [comment]
I have merged the conflicts, but there was a lot (finger crossed).
In events-recurring.php, the line 119 with `recurring-events` (plural) looks suspicious
```PHP
if ( ! is_array( $supports ) || ! in_array( 'recurring-events', $supports[0] ) ) {
```

**Comment by billerickson** [comment]
To enable recurring events you use `add_theme_support( 'be-events-calendar', array( 'recurring-events' ) )` to your theme. I didn't rename that as it semantically matches WP core theme support (ex: `add_theme_support( 'automatic-feed-links' )` ).

**Comment by billerickson** [comment]
Also, it looks like my earlier changes were not included in this. 
- Post thumbnails are no longer on events 
- show_in_menu has been changed from `edit.php?post_type=event` to `true`.
- The post type has been renamed from `recurring_event` to `recurring-event`. WP core standards are to use underscores, like the internal post types; e.g.,  nav_menu_item.
- In manage_event_columns, I had previously changed it to use `$post_id` provided by the function, but that has been undone.
- Some of the 'recurring-events' theme support has been changed to 'recurring-event' (see line 308 of inc/events.php)


I'm going to wait to merge this for a few days, until I have time to also fix these issues directly afterwards.

**Comment by benoitchantre** [comment]
I think I haven't used the best method to solve the conflicts.

Maybe the easier thing would be to start a new branch based on the master branch and to reapply the changes. A lot of them can be applied automatically with PhpStorm.

Let me know what do you think.

**Comment by billerickson** [comment]
Yes, that would be great. If we could have a PR without these breaking changes I could commit it right away.

**Comment by benoitchantre** [comment]
Done. See #38.

**Pull request closed without merging**
