### PR TITLE
Custom date and time format

### PR DESCRIPTION
**Pull request by benoitchantre**
Use the date and time format from the settings

### CODE REVIEW

**Comment by benoitchantre** [comment]
The date and time format aren't internationalized yet in the edit view.

**Comment by benoitchantre** [comment]
Date Month Year format can be set with `add_filter( 'be_event_set_dmy_format', '__return_true' );`
24 hour clock can be set with `add_filter( 'be_event_set_24_hour_clock', '__return_true' );`

For colums, custom formats can be used too with the following filters:

- `be_event_columns_date_format`
- `be_event_columns_time_format`

**Comment by benoitchantre** [comment]
@billerickson Let me know if you some improvements should be done.

**Comment by benoitchantre** [comment]
Custom date and time format for calendar view and widget calendar are not done at the moment.

**Comment by billerickson** [comment]
Instead of having a true/false filter to swap between date formats, why not make the format itself filterable?

```
$date_format    = apply_filters( 'be_events_calendar_date_format', 'm/d/Y' );
```

That way you can change it to any format you prefer - you're not limited to two choices.

**Comment by benoitchantre** [comment]
Because we have different constraints based on the location where the date is displayed :

- columns: we can display the format we want
- fields: we don't have much space and the datepicker doesn't accept all formats

For the event list, there are 2 filters :

- `be_event_columns_date_format`
- `be_event_columns_time_format`

Let me know if it makes sense or if we should replace `be_event_set_dmy_format`, by something like could be`be_event_field_date_format` which would accept a custom date format (same principle for time format).

**Comment by benoitchantre** [comment]
If you have a bit of time @billerickson, can we discuss further to find the best way to handle that? I don't know if you have seen my last comment and if you agree or not with my explanation.

**Comment by billerickson** [comment]
Sorry for the delay. Yes, that makes sense to me.

**Comment by benoitchantre** [comment]
Thank you for having checked that.

**Pull request merged**
